<Project Sdk="MSTest.Sdk/4.3.3">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sigstore\Sigstore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Tuf.Tests\RepositorySimulator.cs"
             Link="TestUtilities\RepositorySimulator.cs" />
  </ItemGroup>

</Project>